---
title: "biomarkers_processing_pipeline"
author: "Clazz"
date: "2025-06-26"
output: html_document
---

```{r}
library(readxl)
#install.packages("ggplot2")
library(ggplot2)
#install.packages("psych")
library(psych)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("ggpubr")
library(ggpubr)
#install.packages("broom")
library(broom)
#install.packages("ggeffects")
library(ggeffects)
#install.packages("MASS")
library(MASS)
#install.packages("PResiduals")
library(PResiduals)
#install.packages("mice")
library(mice)
#install.packages("VIM")
library(VIM)
#install.packages("car")
library(car)
#install.packages("sjPlot")
library(sjPlot)
#install.packages("caret")
library(caret)
#install.packages("bestNormalize")
library(bestNormalize)
#install.packages("ggrain")
library(ggrain)
#install.packages("emmeans")
library(emmeans)
#install.packages("skimr")
library(skimr)
library(glmnet)
#install.packages("bullseye")
library(bullseye)
#install.packages("lavaan")
library(lavaan)
#install.packages("brms")
library(brms)
#install.packages("mgcv")
library(mgcv)
library(splines)
#install.packages("fitdistrplus")
library(fitdistrplus)
#install.packages("patchwork")
library(patchwork)
library(ellmer)
library(gander)
```


#CSF values
```{r}

#ptau181, ttau: elecsys 
#p-tau217 (CSF): In-house  (Thijssen et al. Lancet Neurol 2021)
#Abeta40, Abta42, a-synuclein, IL-6, Neurogranin, NFL, sTREM2: NTK
#GAP43: In-house (Sandelius et al. 2019. PMID 30321501)
#sICAM1, VCAM1: Vascular Injury Panel 2 (human) kits #K15198D
#SNAP25: In-house (Brinkmalm et al. 2014. PMID 25418885)

biomarcadores_CSF <- read_delim("G:/My Drive/Data/ALFA+/biomarkers/Biomarkers_Alfa_Cohort__Biomarkers_alfa_cohort_20241220142704(in).csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)%>%
  dplyr::select(Visit, idparticipante, collection_dt, Assay, SampleType, Result, Kit, ResultRecalc)%>%
  mutate(Kit = factor(Kit),
         SampleType = factor(SampleType),
         Assay = factor(Assay),
         Result= as.numeric(gsub("\\.", "", Result)) / 1000)%>%
  filter(SampleType == "CSF")%>%
  filter(Assay %in% c("a-Synuclein", "Abeta1-40", "Abeta1-42", "GAP43","GFAP", "IL-6", "Neurogranin", "NFL", "pTau181", "pTau217", "sICAM1", "SNAP25", "sTREM2", "sVCAM1","Synaptotagmin", "tTau", "YKL40"))%>%
  unique()%>%
  filter(!(Kit == "Elecsys" & Assay == "Abeta1-42"),
         !(Kit == "In-house (Karikari et al. Lancet Neurol 2020. Suarez-Calvet et al. 2020)" & Assay == "pTau181"),
         !(Kit == "In-house  (Thijssen et al. Lancet Neurol 2021)" & Assay == "tTau"),
         !(Kit == "In-house (Su?rez-Calvet et al. 2020)" & Assay == "pTau217"),
         !(Kit == "NTK" & Assay == "pTau181"),
         !(Kit == "NTK" & Assay == "tTau"),
         !(Kit == "In-house" & Assay == "tTau"),
         !(Kit == "In-house" & Assay == "pTau217"),
         !(Kit == "GFAP Discovery Kit #102336" & Assay == "GFAP"))%>%
  mutate(Result = ifelse(is.na(Result)&!is.na(ResultRecalc), as.numeric(gsub("\\.", "", ResultRecalc)) / 1000, Result))%>%
  dplyr::select(-ResultRecalc)%>%
  dplyr::select(-Kit)%>%
  pivot_wider(names_from = Assay, values_from = Result, names_prefix = "CSF_")%>%
  rename(subject = idparticipante, 
         CSF_Abeta40 = `CSF_Abeta1-40`,
         CSF_Abeta42 = `CSF_Abeta1-42`)%>%
  mutate(CSF_Abeta_ratio = CSF_Abeta42/CSF_Abeta40,
         A = ifelse(CSF_Abeta_ratio>=0.071, 0, 1),
         AT= ifelse(CSF_pTau181<=24.00 & CSF_Abeta_ratio>=0.071, 1, 
                     ifelse(CSF_Abeta_ratio<0.071 & CSF_pTau181<=24.00, 2, 
                            ifelse(CSF_Abeta_ratio>=0.071 & CSF_pTau181>24.00, 3, 4))))%>%
  mutate(A = factor(A),
         AT = factor(AT))



write.csv(biomarcadores_CSF, file = "G:/My Drive/Data/ALFA+/biomarkers/biomarkers_CSF_processed.csv", row.names = F)


#using NTK for amyloid means some NA with abeta42. Is this the best course of action still?
```

#Plasma values
plasma values are a mess - come back to later

```{r}
biomarcadores_PLASMA <- read_delim("G:/My Drive/Data/ALFA+/biomarkers/Biomarkers_Alfa_Cohort__Biomarkers_alfa_cohort_20241220142704(in).csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)%>%
  dplyr::select(Visit, idparticipante, collection_dt, Assay, SampleType, Result, Kit, ResultRecalc)%>%
  mutate(Kit = factor(Kit),
         SampleType = factor(SampleType),
         Assay = factor(Assay),
         Result= as.numeric(gsub("\\.", "", Result)) / 1000)%>%
  filter(SampleType == "PLASMA")%>%
  mutate(Result = ifelse(is.na(Result)&!is.na(ResultRecalc), as.numeric(gsub("\\.", "", ResultRecalc)) / 1000, Result))%>%
  dplyr::select(-ResultRecalc) %>%
  filter(Assay %in% c("a-Synuclein", "Abeta1-40", "Abeta1-42", "GAP43", "GFAP", "IL-6", "Neurogranin", "NFL", "pTau181", "pTau217", "sICAM1", "SNAP25", "sTREM2", "sVCAM1", "Synaptotagmin", "tTau", "YKL40"),
         Visit %in% c("V1", "V2"))
  pivot_wider(names_from = Assay, values_from = Result, names_prefix = "PLASMA_")


```




```{r}
### add PET amyloid 

biomarkers_PET<- read_excel("G:/My Drive/Data/ALFA+/biomarkers/bx_ftm_centiloids_ALFA_PET_FTM_20210421_20250319_141859.xlsx")

biomarkers_PET_A<-biomarkers_PET%>%
  dplyr::select(centiloids, subject)%>%
  mutate(subject = factor(subject))

master_nd<-left_join(master_nd, biomarkers_PET_A)

```