<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Clazz">

<title>Parity and AD specific neurodegeneration</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="paper_ashs_pregnancy_APOE_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_ashs_pregnancy_APOE_files/libs/quarto-html/quarto.js"></script>
<script src="paper_ashs_pregnancy_APOE_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_ashs_pregnancy_APOE_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_ashs_pregnancy_APOE_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_ashs_pregnancy_APOE_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_ashs_pregnancy_APOE_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_ashs_pregnancy_APOE_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_ashs_pregnancy_APOE_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_ashs_pregnancy_APOE_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design"><span class="header-section-number">3.1</span> Study design</a></li>
  <li><a href="#participants" id="toc-participants" class="nav-link" data-scroll-target="#participants"><span class="header-section-number">3.2</span> Participants</a></li>
  <li><a href="#procedures" id="toc-procedures" class="nav-link" data-scroll-target="#procedures"><span class="header-section-number">3.3</span> Procedures</a>
  <ul class="collapse">
  <li><a href="#demographics" id="toc-demographics" class="nav-link" data-scroll-target="#demographics"><span class="header-section-number">3.3.1</span> Demographics</a></li>
  <li><a href="#imaging-data-preprocessing" id="toc-imaging-data-preprocessing" class="nav-link" data-scroll-target="#imaging-data-preprocessing"><span class="header-section-number">3.3.2</span> Imaging data preprocessing</a></li>
  <li><a href="#automatic-segmentation-of-hippocampal-subfields" id="toc-automatic-segmentation-of-hippocampal-subfields" class="nav-link" data-scroll-target="#automatic-segmentation-of-hippocampal-subfields"><span class="header-section-number">3.3.3</span> Automatic Segmentation of Hippocampal Subfields</a></li>
  <li><a href="#lumbar-puncture" id="toc-lumbar-puncture" class="nav-link" data-scroll-target="#lumbar-puncture"><span class="header-section-number">3.3.4</span> Lumbar puncture</a></li>
  <li><a href="#cognitive-measures" id="toc-cognitive-measures" class="nav-link" data-scroll-target="#cognitive-measures"><span class="header-section-number">3.3.5</span> Cognitive measures</a></li>
  </ul></li>
  <li><a href="#statistical-analyses" id="toc-statistical-analyses" class="nav-link" data-scroll-target="#statistical-analyses"><span class="header-section-number">3.4</span> Statistical analyses</a>
  <ul class="collapse">
  <li><a href="#linear-regression-models" id="toc-linear-regression-models" class="nav-link" data-scroll-target="#linear-regression-models"><span class="header-section-number">3.4.1</span> Linear regression models</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#descriptive-results" id="toc-descriptive-results" class="nav-link" data-scroll-target="#descriptive-results"><span class="header-section-number">4.1</span> Descriptive results</a></li>
  <li><a href="#whole-hippocampal-volume" id="toc-whole-hippocampal-volume" class="nav-link" data-scroll-target="#whole-hippocampal-volume"><span class="header-section-number">4.2</span> Whole Hippocampal volume</a></li>
  <li><a href="#cognitive-trajectory" id="toc-cognitive-trajectory" class="nav-link" data-scroll-target="#cognitive-trajectory"><span class="header-section-number">4.3</span> Cognitive trajectory</a></li>
  <li><a href="#post-hoc-analyses" id="toc-post-hoc-analyses" class="nav-link" data-scroll-target="#post-hoc-analyses"><span class="header-section-number">4.4</span> Post-hoc analyses</a>
  <ul class="collapse">
  <li><a href="#influence-of-amyloid" id="toc-influence-of-amyloid" class="nav-link" data-scroll-target="#influence-of-amyloid"><span class="header-section-number">4.4.1</span> Influence of Amyloid</a></li>
  <li><a href="#hippocampal-subfields" id="toc-hippocampal-subfields" class="nav-link" data-scroll-target="#hippocampal-subfields"><span class="header-section-number">4.4.2</span> Hippocampal subfields</a></li>
  <li><a href="#stratification" id="toc-stratification" class="nav-link" data-scroll-target="#stratification"><span class="header-section-number">4.4.3</span> Stratification</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="header-section-number">6</span> Appendix</a>
  <ul class="collapse">
  <li><a href="#mri-data-acquisition" id="toc-mri-data-acquisition" class="nav-link" data-scroll-target="#mri-data-acquisition"><span class="header-section-number">6.1</span> MRI data acquisition</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="paper_ashs_pregnancy_APOE.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Parity and AD specific neurodegeneration</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Clazz </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abstract</h1>
<p>300 words</p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>Alzhimer’s disease (AD) is a neurodegenerative disorder clinically characteized by progressive memory loss. Ageing, carring the apolipoprotein E E4 (APOE4) and having female chromosomal sex are three established risk factors for the typical late-onset of this disease <span class="citation" data-cites="riedel2016">[<a href="#ref-riedel2016" role="doc-biblioref">1</a>]</span>. Carrying one copy of APOE4 increases AD risk by three to four fold, whilst carrying 2 copies skyrockets that risk to 10 folds <span class="citation" data-cites="corder1993">[<a href="#ref-corder1993" role="doc-biblioref">2</a>]</span>. Women have a higher incidence of late-onset AD dementia <span class="citation" data-cites="beam2018">[<a href="#ref-beam2018" role="doc-biblioref">3</a>]</span> and show faster cognitive decline after diagnosis of MCI or AD dementia <span class="citation" data-cites="sexdiff2018">[<a href="#ref-sexdiff2018" role="doc-biblioref">4</a>]</span>. Amongst APOE4 carriers, women exhibit an increased risk of conversion from healthy ageing to MCI, or from MCI to AD dementia between the ages of 65 to 75 <span class="citation" data-cites="Altmann2014 Neu2017">[<a href="#ref-Altmann2014" role="doc-biblioref">5</a>,<a href="#ref-Neu2017" role="doc-biblioref">6</a>]</span>. Thus to understand sex differences in AD risk it is essential to understand how these non-modifyable risk factors interact.</p>
<p>The hippocampus is one of the first regions affected by AD, and whole hippocampal volume is a hallmark predictor of conversion from MCI to AD <span class="citation" data-cites="apostolova2006">[<a href="#ref-apostolova2006" role="doc-biblioref">7</a>]</span>. one of its particularity resides in its display of continuous neurogenesis throughout adult life <span class="citation" data-cites="boldrini2018">[<a href="#ref-boldrini2018" role="doc-biblioref">8</a>]</span>. The hippocampus is not a homogenous structure, but is divided in anatomical subfields that show different molecular makeup () and a degree of cognitive specialization <span class="citation" data-cites="mueller2011">[<a href="#ref-mueller2011" role="doc-biblioref">9</a>]</span>. Altered neurogenesis is linked to AD related neuropathology and impairments in cognition <span class="citation" data-cites="hollands2017">[<a href="#ref-hollands2017" role="doc-biblioref">10</a>]</span>.</p>
<p>Pregnancy provokes significant changes to brain structure via major hormonal changes which impact the hippocampus in a lasting way <span class="citation" data-cites="puri2023">[<a href="#ref-puri2023" role="doc-biblioref">11</a>]</span>. Animal models show decreased neurogenesis in the hippocampus during gestation and postpartum period [<span class="citation" data-cites="pawluski2007">[<a href="#ref-pawluski2007" role="doc-biblioref">12</a>]</span>; <span class="citation" data-cites="eid2019">[<a href="#ref-eid2019" role="doc-biblioref">13</a>]</span>]. In humans, pregnancy is associated with a total hippocampal volume loss which then recovers in the next two years post partum <span class="citation" data-cites="Hoekzema2017">[<a href="#ref-Hoekzema2017" role="doc-biblioref">14</a>]</span>. Currently, there is a lack of data on how these mid-life changes affect the hippocampus in older adults, and wether they have consequences on cognition.</p>
<p>Evidence on how previous pregnancies influence ageing and AD risk is conflicting. Previous parity has been linked with less apparent brain ageing <span class="citation" data-cites="de2020">[<a href="#ref-de2020" role="doc-biblioref">15</a>]</span>. But amongst epidemiological studies that explored a potential association between parity and AD, some report a link between multiparity and greater cognitive decline <span class="citation" data-cites="colucci2006">[<a href="#ref-colucci2006" role="doc-biblioref">16</a>]</span>, whilst other report no link or the opposite findings <span class="citation" data-cites="Fox2018 Fox2013 wolfova2024">[<a href="#ref-Fox2018" role="doc-biblioref">17</a>,<a href="#ref-Fox2013" role="doc-biblioref">18</a>.,<a href="#ref-wolfova2024" role="doc-biblioref">19</a>]</span> To our knowledge, only two studies so far have included AD biomarkers as a dependent variable, and whilst one repports a positive relationship between amyloid plaques and parity, the other does not<span class="citation" data-cites="Beeri2009a Jung2020">[<a href="#ref-Beeri2009a" role="doc-biblioref">20</a>,<a href="#ref-Jung2020" role="doc-biblioref">21</a>]</span>. Together, these studies indicate that although a link might exist between parity and AD, it is not well characterized and shows mixed direction of effect.</p>
<p>Recently, Bee and colleagues (2024) <span class="citation" data-cites="lee2024">[<a href="#ref-lee2024" role="doc-biblioref">22</a>]</span> presented the first evidence for an interaction between APOE4 and parity in animals. Using wildtype and humanized APOE4 knock-in middle aged female rats, they found that whilst parity increased neurogenesis in wildtype rats, it decreased it in APOE4 rats, especially in the ventral dentate gyrus. In addition to this, parous APOE4 rats showed increased use of allocentric strategy instead of spatial when solving spatial memory tasks, suggesting a decreased recruitment of the hippocampus. Importantly, this aligns with previous literature reporting a link between AD dementia and decreased use of spatial strategy in humans <span class="citation" data-cites="parizkova2018">[<a href="#ref-parizkova2018" role="doc-biblioref">23</a>]</span>. To our knowledge, no study has explored this interaction of APOE4 and parity on hippocampal structure in humans.</p>
<p>Our objective was to explore potential links and mechanisms through which pregnancy interacts with AD pathology in healthy postmenopausal women at risk of AD. To this end, we used hippocampal volumetry drawn from MRI data, biomarker data, cogntive data and reproductive data from two initial visits from the ALFA+cohort. We hypothesized that parous women would show decreased whole hippocampal volume loss but this relationship would be inversed in APOE4 carriers.</p>
</section>
<section id="methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methods</h1>
<section id="study-design" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="study-design"><span class="header-section-number">3.1</span> Study design</h2>
<p>This study was realised within the context of the The ALFA+ project, a longitudinal observational cohort of healthly middle aged adults. This project currently takes place in the city of Barcelona, Spain, at the BarcelonaBeta Brain Research Center. Visit 1 was collected between 2013 and 2015, and Visit 2 between 2016 and 2019 Visit 3 is still undergoing. The ALFA study protocol was approved by the Independent Ethics Committee Parc de Salut Mar Barcelona (and registered at Clinicaltrials.gov, NCT01835717). For a more detailed description of the cohort see Molinuevo et al.<span class="citation" data-cites="molinuevo2016">[<a href="#ref-molinuevo2016" role="doc-biblioref">24</a>]</span>.</p>
</section>
<section id="participants" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="participants"><span class="header-section-number">3.2</span> Participants</h2>
<p>In brief, inclusion criteria were being cognitively normal, Spanish and/or Catalan-speaking, being aged between 45 and 74 years and agreing with the study procedures and tests. A close relative was involved in the volunteer’s functional evaluation and both of them had to grant their written informed consent. Exclusion criterias Exclusion criteria were (1) Cognitive performance falling outside the established cutoffs, (2) a Clinical Dementia Rating above 0, (3) major psychiatric disorders (according to DSM-IV-TR), (4) Severe auditory and/or visual disorder, neurodevelopmental and/or psychomotor disorder, (5) Signiﬁcant diseases that could currently interfere with cognition, (6) neurological disorders, (7) Brain injuries and (8) a suspected pattern of family autosomal dominant AD.</p>
<p>In addition to the above exclusion criteria, women with history of cardiovascular related gestational disease, such as preeclampsia, were excluded from our sample for analysis.</p>
<p>Participants were recruited via advertisement campaigns in newspapers and followed-up via email/phonecalls.</p>
<ul>
<li>Loss to follow-up? do we have data on that?</li>
</ul>
</section>
<section id="procedures" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="procedures"><span class="header-section-number">3.3</span> Procedures</h2>
<section id="demographics" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="demographics"><span class="header-section-number">3.3.1</span> Demographics</h3>
<p>Demographic data was collected via oral questions administered by a clinician. Sex was self reported, as well as gender and participants could choose from three options: male, female, or … Race and ethnicity were also self-reported. There was no report of biological sex and gender being different in our cohort, therefore the word ‘women’ will be used to refer to our female subjects.</p>
<p>Reproductive variables, such as number of biological kids, age at menopause, age at menarche and number of abortions, were self-reported at the baseline visit. In the subsequent visits, participants were also asked about hormonal replacement therapy.</p>
<p>Social variables such as years of education, household income, occupational attainment and civil status were also self-reported at baseline visit.</p>
</section>
<section id="imaging-data-preprocessing" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="imaging-data-preprocessing"><span class="header-section-number">3.3.2</span> Imaging data preprocessing</h3>
<p>GMV changes were computed voxel-wise using the pairwise longitudinal registration implemented in the statistical parametric mapping software (SPM, version 12) (<a href="https://www.fil.ion.ucl.ac.uk/spm/software/spm12/"><strong>https://www.fil.ion.ucl.ac.uk/spm/software/spm12/</strong></a>). The procedure involves a high-dimensional warping between consecutive T1-weighted scans, combining diffeomorphic and rigid-body registrations and incorporating a correction for field inhomogeneities. This procedure yields for each subject a parametric whole brain map encoding at each voxel the local tissue deformations that have occurred over time <span class="citation" data-cites="Ashburner2007">[<a href="#ref-Ashburner2007" role="doc-biblioref">25</a>]</span>.&nbsp;Individual deformation maps were inspected for sample homogeneity using the computational anatomy toolbox (CAT12) (<a href="http://dbm.neuro.unijena.de/cat/"><strong>http://dbm.neuro.unijena.de/cat/</strong></a>) and normalized to the Montreal Neurological Institute (MNI) space using diffeomorphic image registration with DARTEL30&nbsp;and spatially smoothed with an 8-mm full width at half maximum (FWHM) Gaussian kernel before being submitted to group statistical analyses.</p>
</section>
<section id="automatic-segmentation-of-hippocampal-subfields" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="automatic-segmentation-of-hippocampal-subfields"><span class="header-section-number">3.3.3</span> Automatic Segmentation of Hippocampal Subfields</h3>
<p>Automatic Segmentation of Hippocampal Subfields (ASHS) software <span class="citation" data-cites="Yushkevich2015">[<a href="#ref-Yushkevich2015" role="doc-biblioref">26</a>]</span>&nbsp;was used on the T1 and inversion recovery (IR) images to segment the hippocampal formation in the following sub-regions: Brodmann areas 35 and 36, cornu Ammonis (CA) 1, 2 and 3, dentate gyrus (DG), entorhinal cortex (ERC), parahippocampus (PHC), subiculum (SUB), and sulcus (SUL). All segmentations were visually inspected before proceeding with the statistical analyses.</p>
</section>
<section id="lumbar-puncture" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4" class="anchored" data-anchor-id="lumbar-puncture"><span class="header-section-number">3.3.4</span> Lumbar puncture</h3>
<p>CSF was collected by lumbar puncture between 9 and 12 a.m. in polypropylene tubes. Samples were processed within 1 hour and centrifuged at 4°C for 10 minutes at 2000 g, stored in polypropylene tubes and frozen at -80°C. Core AD biomarkers (namely Aß42, Ab40, total Tau, and p tau) and other molecules of interest (such as YKL-40, neurogranin and Ab oligomers) were analyzed and determined in Prof.&nbsp;Kaj Blennow’s laboratory (Institute ofNeuroscience and Physiology, Department of Psychiatry and Neurochemistry, The Sahlgrenska Academy at the University of Gothenburg, Sweden).</p>
</section>
<section id="cognitive-measures" class="level3" data-number="3.3.5">
<h3 data-number="3.3.5" class="anchored" data-anchor-id="cognitive-measures"><span class="header-section-number">3.3.5</span> Cognitive measures</h3>
<p>The Preclinical Alzheimer Cognitive Composite (PACC) was developed to detect subtle cognitive changes in individuals who may be in the pre-clinical stages of AD <span class="citation" data-cites="Donohue2014">[<a href="#ref-Donohue2014" role="doc-biblioref">27</a>]</span>, and includes elements of the Memory Binding Test, the Coding subtest of WAIS-IV, and semantic fluency. Z-scores were computed for Visit 1 and 2.</p>
</section>
</section>
<section id="statistical-analyses" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="statistical-analyses"><span class="header-section-number">3.4</span> Statistical analyses</h2>
<section id="linear-regression-models" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="linear-regression-models"><span class="header-section-number">3.4.1</span> Linear regression models</h3>
<p>Statistical analyses were carried using R v4.5.1. Our exposure variables included parity, time and Aβ positivity. Parity was defined as number of biological children and used as a continuous variable (1, 2, 3, 4+). In order to explore the potential non-linear effects, we grouped subjects by nulliparous, primiparous and multiparous. Time was assessed as number of days between either MRI scans or cognitive testing sessions at visit 1 and 2. Aβ pathology was defined as the ratio of CSF Aß42 over CSF Aß40. All analyses were stratified by sex.</p>
<p>To identify other potential confounders in our primary analyses, we used directed acyclic graph (DAG) methodology to aid with covariate selection. Using Pearl’s backdoor criteria, we decided to covary for education in all our analyses given that the effet of this variable on both the exposure and outcome variable, therefore making it a cofounding variable in our analyses along with age at baseline. All linear regressions were also adjusted for age at baseline, time and CSF Aß42/40 ratio. Linear regressions with hippocampal subfield volumes as outcomes were adjusted for Total Intracranial Volume (TIV).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="paper_ashs_pregnancy_APOE_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We first carried out linear mixed-effect models including parity and time as exposure and hippocampal volume as outcome. Covariates weere age at baseline visit, education, CSF Aß42/40, and total intracranial volume. APOE4 carriership were then introduced as a moderator. These analyses were reproduced using PACC as outcome. For post-hoc analyses we tested the same interaction on hippocampal subfields. Due to the exploratory nature of these subsequent analyses, results are reported uncorrected.</p>
<p>Data imputation methods were implemented using the mice package in R (v.3.18.0) on covariates, but not exposure or outcome variables. For continous variables, predictive mean matching with 5 donors was used. For categorical variables, logistic regression was used.</p>
<p>This analysis is opportunistic, in the sense that the ALFA+ cohort was designed to provide data for a wide range of questions. Consequently, this study sample size limits the kind of analysis we are able to perform. Because of this, we chose not to include results from stratified analysis in this paper because of a high chance of yielding type II errors.</p>
</section>
</section>
</section>
<section id="results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<section id="descriptive-results" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="descriptive-results"><span class="header-section-number">4.1</span> Descriptive results</h2>
<div class="cell">
<div class="cell-output-display">
<div id="cjrvketnvy" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#cjrvketnvy table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#cjrvketnvy thead, #cjrvketnvy tbody, #cjrvketnvy tfoot, #cjrvketnvy tr, #cjrvketnvy td, #cjrvketnvy th {
  border-style: none;
}

#cjrvketnvy p {
  margin: 0;
  padding: 0;
}

#cjrvketnvy .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cjrvketnvy .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cjrvketnvy .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cjrvketnvy .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cjrvketnvy .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cjrvketnvy .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cjrvketnvy .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cjrvketnvy .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cjrvketnvy .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cjrvketnvy .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cjrvketnvy .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cjrvketnvy .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cjrvketnvy .gt_spanner_row {
  border-bottom-style: hidden;
}

#cjrvketnvy .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cjrvketnvy .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cjrvketnvy .gt_from_md > :first-child {
  margin-top: 0;
}

#cjrvketnvy .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cjrvketnvy .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cjrvketnvy .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cjrvketnvy .gt_row_group_first td {
  border-top-width: 2px;
}

#cjrvketnvy .gt_row_group_first th {
  border-top-width: 2px;
}

#cjrvketnvy .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cjrvketnvy .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cjrvketnvy .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cjrvketnvy .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cjrvketnvy .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#cjrvketnvy .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cjrvketnvy .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cjrvketnvy .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cjrvketnvy .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cjrvketnvy .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_left {
  text-align: left;
}

#cjrvketnvy .gt_center {
  text-align: center;
}

#cjrvketnvy .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cjrvketnvy .gt_font_normal {
  font-weight: normal;
}

#cjrvketnvy .gt_font_bold {
  font-weight: bold;
}

#cjrvketnvy .gt_font_italic {
  font-style: italic;
}

#cjrvketnvy .gt_super {
  font-size: 65%;
}

#cjrvketnvy .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#cjrvketnvy .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cjrvketnvy .gt_indent_1 {
  text-indent: 5px;
}

#cjrvketnvy .gt_indent_2 {
  text-indent: 10px;
}

#cjrvketnvy .gt_indent_3 {
  text-indent: 15px;
}

#cjrvketnvy .gt_indent_4 {
  text-indent: 20px;
}

#cjrvketnvy .gt_indent_5 {
  text-indent: 25px;
}

#cjrvketnvy .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#cjrvketnvy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Number of childbirths</strong></th>
<th id="n" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>N</strong></th>
<th id="stat_1" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>0</strong><br>
N = 66<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_2" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>1</strong><br>
N = 93<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_3" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>2</strong><br>
N = 214<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_4" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>3</strong><br>
N = 47<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_5" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>4</strong><br>
N = 12<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">Age at first visit, Mean (SD)</td>
<td class="gt_row gt_center" headers="n">432</td>
<td class="gt_row gt_center" headers="stat_1">58.5 (55.3, 63.1)</td>
<td class="gt_row gt_center" headers="stat_2">62.5 (57.6, 64.9)</td>
<td class="gt_row gt_center" headers="stat_3">62.5 (58.8, 65.1)</td>
<td class="gt_row gt_center" headers="stat_4">61.2 (57.7, 64.7)</td>
<td class="gt_row gt_center" headers="stat_5">63.4 (59.8, 66.9)</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">Aβ status, Count (%)</td>
<td class="gt_row gt_center" headers="n">383</td>
<td class="gt_row gt_center" headers="stat_1"><br>
</td>
<td class="gt_row gt_center" headers="stat_2"><br>
</td>
<td class="gt_row gt_center" headers="stat_3"><br>
</td>
<td class="gt_row gt_center" headers="stat_4"><br>
</td>
<td class="gt_row gt_center" headers="stat_5"><br>
</td>
<td class="gt_row gt_center" headers="p.value">0.4</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Aβ-</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_1">41 (71%)</td>
<td class="gt_row gt_center" headers="stat_2">59 (71%)</td>
<td class="gt_row gt_center" headers="stat_3">114 (62%)</td>
<td class="gt_row gt_center" headers="stat_4">32 (70%)</td>
<td class="gt_row gt_center" headers="stat_5">6 (50%)</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Aβ+</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_1">17 (29%)</td>
<td class="gt_row gt_center" headers="stat_2">24 (29%)</td>
<td class="gt_row gt_center" headers="stat_3">70 (38%)</td>
<td class="gt_row gt_center" headers="stat_4">14 (30%)</td>
<td class="gt_row gt_center" headers="stat_5">6 (50%)</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">APOE-E4 carrier, Count (%)</td>
<td class="gt_row gt_center" headers="n">431</td>
<td class="gt_row gt_center" headers="stat_1"><br>
</td>
<td class="gt_row gt_center" headers="stat_2"><br>
</td>
<td class="gt_row gt_center" headers="stat_3"><br>
</td>
<td class="gt_row gt_center" headers="stat_4"><br>
</td>
<td class="gt_row gt_center" headers="stat_5"><br>
</td>
<td class="gt_row gt_center" headers="p.value">0.11</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Carrier</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_1">33 (51%)</td>
<td class="gt_row gt_center" headers="stat_2">44 (47%)</td>
<td class="gt_row gt_center" headers="stat_3">129 (60%)</td>
<td class="gt_row gt_center" headers="stat_4">27 (57%)</td>
<td class="gt_row gt_center" headers="stat_5">4 (33%)</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Non-Carrier</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_1">32 (49%)</td>
<td class="gt_row gt_center" headers="stat_2">49 (53%)</td>
<td class="gt_row gt_center" headers="stat_3">85 (40%)</td>
<td class="gt_row gt_center" headers="stat_4">20 (43%)</td>
<td class="gt_row gt_center" headers="stat_5">8 (67%)</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">Time between visits (years), Mean (SD)</td>
<td class="gt_row gt_center" headers="n">353</td>
<td class="gt_row gt_center" headers="stat_1">3.24 (3.01, 3.47)</td>
<td class="gt_row gt_center" headers="stat_2">3.34 (3.13, 3.58)</td>
<td class="gt_row gt_center" headers="stat_3">3.15 (2.97, 3.44)</td>
<td class="gt_row gt_center" headers="stat_4">3.24 (3.03, 3.65)</td>
<td class="gt_row gt_center" headers="stat_5">3.50 (3.03, 3.76)</td>
<td class="gt_row gt_center" headers="p.value">0.023</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">Education (years), Mean (SD)</td>
<td class="gt_row gt_center" headers="n">432</td>
<td class="gt_row gt_center" headers="stat_1">15.5 (12.0, 18.0)</td>
<td class="gt_row gt_center" headers="stat_2">12.0 (11.0, 17.0)</td>
<td class="gt_row gt_center" headers="stat_3">12.0 (10.0, 17.0)</td>
<td class="gt_row gt_center" headers="stat_4">16.0 (11.0, 18.0)</td>
<td class="gt_row gt_center" headers="stat_5">12.0 (9.0, 17.0)</td>
<td class="gt_row gt_center" headers="p.value">0.009</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="odd">
<td colspan="8" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Median (Q1, Q3); n (%)</td>
</tr>
<tr class="even">
<td colspan="8" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> Kruskal-Wallis rank sum test; Fisher’s exact test; Pearson’s Chi-squared test</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>432 participants from the ALFA+ project were included in our analyses, of which 254 are women. Visit 1 included MRI data from 411 participants, cognitive testing from 417 participants and CSF biomarkers from 400 participants. Visit 2 included MRI data from 353 participants, cognitive testing from 367 participants and CSF biomarkers from 277 participants. Average time between visits was 3.32 years.</p>
<p>Table 1 shows demographics and characteristics of the ALFA+ cohort for all aprticipants included in Visit 1, grouped by parity. Participants with higher parity were significantly more likely to be older. Participants with more number of childbirths were significantly more likely to have less years of education. No difference was seen between groups regarding Aβ status and APOE-ε4 carriership.</p>
</section>
<section id="whole-hippocampal-volume" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="whole-hippocampal-volume"><span class="header-section-number">4.2</span> Whole Hippocampal volume</h2>
<p>We found no significant independent effect of parity on whole hippocampal volume. However, a highly significant parity, APOE-E4 and time interaction was found (β = -34.656, SE = 8.446, p = 6.06^{-5}), such that over time, homozygote APOE-E4 carrier women showed a negative relationship between parity and hippocampal volume, whilst non-carriers women showed the opposite. When grouping the variable by nulliparous, primiparous or multiparous, that same three-way interaction was stronger and only significant for multiparous women (β = 2.84, SE = 18.515, p = 0.878) (Figure X).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="paper_ashs_pregnancy_APOE_files/figure-html/graph%20whole%20hippocampus-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="paper_ashs_pregnancy_APOE_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No main effect of parity or interaction with APOE-E4 carriership was found in men.</p>
</section>
<section id="cognitive-trajectory" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="cognitive-trajectory"><span class="header-section-number">4.3</span> Cognitive trajectory</h2>
<p>The interaction between time, APOE4 and parity was not significant. However, the interaction between parity and APOE4 yielded a weak trend (ß = -0.156, p= 0.094). In comparison, using parous group as an interaction term did no yield any significant results.</p>
<p>No significant effect was found in men.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="paper_ashs_pregnancy_APOE_files/figure-html/graph%20cog-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="post-hoc-analyses" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="post-hoc-analyses"><span class="header-section-number">4.4</span> Post-hoc analyses</h2>
<section id="influence-of-amyloid" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="influence-of-amyloid"><span class="header-section-number">4.4.1</span> Influence of Amyloid</h3>
</section>
<section id="hippocampal-subfields" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="hippocampal-subfields"><span class="header-section-number">4.4.2</span> Hippocampal subfields</h3>
<p>Similarly, no significant main effect of parity was found in any of the subfields. However, the 3-way interaction between APOE-E4 carrership, time and parity showed a significant effect on the CA1 volume (β = -13.846, SE = 6.429, p = 0.033), CA2 (β = -0.776, SE = 0.245, p = 0.002), subiculum (β = -4.346, SE = 1.828, p = 0.018), entorhinal cortex (β = -9.673, SE = 4.18, p = 0.022), and a trend in the dentate gyrus (β = -12.059, SE = 6.675, p = 0.072). The direction of the effect followed the same as for the whole hippocampus, where Aβ- women showed a positive relationship between parity and hippocampal volume over time, whilst Aβ- women showed the opposite (Figure X) - should I include the parous gorup results too? or adds too much complexity?</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="paper_ashs_pregnancy_APOE_files/figure-html/graph%20subfields-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="stratification" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="stratification"><span class="header-section-number">4.4.3</span> Stratification</h3>
</section>
</section>
</section>
<section id="discussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion</h1>
<p>Our study aimed to investigate the impact of parity on hippocampal subfield volumes and relation to the APOE4 allele in post-menopausal women at risk of AD. Our results suggest that parity and AD specific genotype interact in women to impact hippocampal volume loss. In our sample, multiparous APOE4 non-carriers showed less hippocampus volume decline, whilst multiparous APOE4 carriers showed worse cognitive decline. These rseults show evidence of an interaction between parity and AD related genetic risk in women, which is associated in volume loss in a brain region which is a prime marker of AD. Essentially, this evidence strongly suggests there is a clear biological component to the interaction between parity and AD risk in women.</p>
<p>When using the categorical grouping for parity, results showed significantly bigger effect in multiparous women. This could indicate that the cumulative effects of parity are only significantly interact with genetic risk after having had more than one child. However, it is important to note that the multiparous groups had a fairly larger number of observations than the nulliparous or primiparous group, therefore lack of significance might indicate a power issue when performing the gorup interaction.</p>
<p>The AFLFA+ cohort is an ideal cohort to test this interaction, given the participants are enriched in genetic AD risk, As such, about 40% of our cohort is a carrier of the APOE4 allele, meaning group interactions are very balanced statistically.</p>
<p>Our findings reproduce the ones found by Bee and colleagues. Similarly, APOE4 carriers show detrimental effects of parity on hhippocampal volume trajectory. Although we did not replicate their findings on memory, this could be due to the relative short amount of time between both visits, on 3 years in average. However, another hypothesis could be that there are intricate social factors at play in humans revolving around parity, which could be influencing cognitive resilience. A previous study done with the UK biobank also finds no effect of the interaction between APOE4 and parity on cognitive score (lindseth et al 2023), although their battery of test is limited.</p>
<p>Our post-hoc analysis of hippocampal subfields shows the most affected regions are the CA1, CA2, subiculum and enthorinal cortex, and a trend in the dentate gyrus. Given Bee’s results, one could expect a stornger effect in the dentate gyrus, given most of the effect of parity in neurogenesis would reside in this subfield. The strong effect on parts of the cornu ammonis also reveals ageing mechanism.</p>
<p>Subiculum linked with early AD apthology. and ERC?</p>
<p>Older EPOE4 carriers show reduced hippocampal volume compared with non-carriers, especially in the CA1 and subiculum tissue <span class="citation" data-cites="pievani2011">[<a href="#ref-pievani2011" role="doc-biblioref">28</a>]</span>.</p>
<p>A limitation of this study is the lack of a third timepoint, to examine potential non linear effects throuhg time. Some preliminary evidence suggests that during pregnancy, hippocampal reduction pattern might follow different progresison curves depending on the subfield, with the CA showing a U-curved shaped loss pattern and the para-hippocampal cortex (PHC) a linear pattern <span class="citation" data-cites="pritschet2024">[<a href="#ref-pritschet2024" role="doc-biblioref">29</a>]</span>.</p>
<p>Another limitation is statistical power. Although the ALFA+ cohort draws its strenght in the richness of the information collected form its participants, but its size remains limites for complex analyses. The stratification of analyses by gender already reduces our sample by half, and gorup interaction by APOE4 splits it further.</p>
<p>Another limitation is that the ALFA+ cohort is very homogeneous: participants are majoritarily caucasian whites, from middle and upper-middle class background, who were selected due to their impeccable health records. Therefore, we must use cuation when generalising our results to a wider population. Additionally, our sample lacked highly multiparous individuals. Previous studies on the effect of parity on cognition and neurodegeneration have found an inverted u-shaped relation between parity and outcome measures, indicating that our lack of women having had more than 4 children might be leading to an incomplete picture of the phenomenon.</p>
</section>
<section id="appendix" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Appendix</h1>
<section id="mri-data-acquisition" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="mri-data-acquisition"><span class="header-section-number">6.1</span> MRI data acquisition</h2>
<p>MRI scans were acquired on a in-house 3.0 T scanner (GE Discovery MR750 W 3 T) using the same protocol for all participants, which included one T1- and three T2- weighted sequences. The 3D-T1w sequence was designed with an isotropic voxel size of1mm3 and a matrix size of256x256x160 (TR/TE/TI = 8.0/3.7/450 ms, NSA = 1, flip angle = 8°). Three 3D-T2w sequences, with a voxel size of1 mm× 1 mm× 3 mm, were also used: fluid attenuation inversion recovery (FLAIR: TR/TE/ TI = 11,000/90/2600 ms, flip angle = 160°), fast spin echo (FSE: TR/TE = 5000/85 ms, flip angle = 110°) and, gradient echo (GRE: TR/TE = 1300/23 ms, flip angle = 15°). All scans were visually assessed to verify their quality and to detect incidental findings by a trained neuroradiologist and have been reported elsewhere (Brugulat-Serrat et al.&nbsp;2017). At visit 1, ten participants were excluded due to the presence of a meningioma, as well as 37 participants due to susceptibility, motion artefacts or segmentation problems, resulting in a total of 561 images available for subsequent analysis. At Visit 2, … The medial temporal lobe atrophy was assessed by Medial Temporal Atrophy scale <span class="citation" data-cites="scheltens1992a">[<a href="#ref-scheltens1992a" role="doc-biblioref">30</a>]</span>.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-riedel2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">Riedel BC, Thompson PM, Brinton RD. Age, APOE and sex: Triad of risk of Alzheimer<span>’</span>s disease. The Journal of Steroid Biochemistry and Molecular Biology 2016;160:134–47. <a href="https://doi.org/10.1016/j.jsbmb.2016.03.012">https://doi.org/10.1016/j.jsbmb.2016.03.012</a>.</div>
</div>
<div id="ref-corder1993" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">Corder EH, Saunders AM, Strittmatter WJ, Schmechel DE, Gaskell PC, Small GW, et al. Gene Dose of Apolipoprotein E Type 4 Allele and the Risk of Alzheimer’s Disease in Late Onset Families. Science 1993;261:921–3. <a href="https://doi.org/10.1126/science.8346443">https://doi.org/10.1126/science.8346443</a>.</div>
</div>
<div id="ref-beam2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">Beam CR, Kaneshiro C, Jang JY, Reynolds CA, Pedersen NL, Gatz M. Differences Between Women and Men in Incidence Rates of Dementia and Alzheimer<span>’</span>s Disease. Journal of Alzheimer<span>’</span>s Disease 2018;64:1077–83. <a href="https://doi.org/10.3233/jad-180141">https://doi.org/10.3233/jad-180141</a>.</div>
</div>
<div id="ref-sexdiff2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">Ferretti MT, Iulita MF, Cavedo E, Chiesa PA, Schumacher Dimech A, Santuccione Chadha A, et al. Sex differences in Alzheimer disease <span></span> the gateway to precision medicine. Nature Reviews Neurology 2018;14:457–69. <a href="https://doi.org/10.1038/s41582-018-0032-9">https://doi.org/10.1038/s41582-018-0032-9</a>.</div>
</div>
<div id="ref-Altmann2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">Altmann A, Tian L, Henderson VW, Greicius MD. Sex modifies the <span><em>APOE</em></span><span>-</span>related risk of developing Alzheimer disease. Annals of Neurology 2014;75:563–73. <a href="https://doi.org/10.1002/ana.24135">https://doi.org/10.1002/ana.24135</a>.</div>
</div>
<div id="ref-Neu2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline">Neu SC, Pa J, Kukull W, Beekly D, Kuzma A, Gangadharan P, et al. Apolipoprotein E Genotype and Sex Risk Factors for Alzheimer Disease. JAMA Neurology 2017;74:1178. <a href="https://doi.org/10.1001/jamaneurol.2017.2188">https://doi.org/10.1001/jamaneurol.2017.2188</a>.</div>
</div>
<div id="ref-apostolova2006" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div><div class="csl-right-inline">Apostolova LG, Dutton RA, Dinov ID, Hayashi KM, Toga AW, Cummings JL, et al. Conversion of Mild Cognitive Impairment to Alzheimer Disease Predicted by Hippocampal Atrophy Maps. Archives of Neurology 2006;63:693. <a href="https://doi.org/10.1001/archneur.63.5.693">https://doi.org/10.1001/archneur.63.5.693</a>.</div>
</div>
<div id="ref-boldrini2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">[8] </div><div class="csl-right-inline">Boldrini M, Fulmore CA, Tartt AN, Simeon LR, Pavlova I, Poposka V, et al. Human Hippocampal Neurogenesis Persists throughout Aging. Cell Stem Cell 2018;22:589–599.e5. <a href="https://doi.org/10.1016/j.stem.2018.03.015">https://doi.org/10.1016/j.stem.2018.03.015</a>.</div>
</div>
<div id="ref-mueller2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">[9] </div><div class="csl-right-inline">Mueller SG, Chao LL, Berman B, Weiner MW. Evidence for functional specialization of hippocampal subfields detected by MR subfield volumetry on high resolution images at 4T. NeuroImage 2011;56:851–7. <a href="https://doi.org/10.1016/j.neuroimage.2011.03.028">https://doi.org/10.1016/j.neuroimage.2011.03.028</a>.</div>
</div>
<div id="ref-hollands2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[10] </div><div class="csl-right-inline">Hollands C, Tobin MK, Hsu M, Musaraca K, Yu T-S, Mishra R, et al. Depletion of adult neurogenesis exacerbates cognitive deficits in Alzheimer<span>’</span>s disease by compromising hippocampal inhibition. Molecular Neurodegeneration 2017;12. <a href="https://doi.org/10.1186/s13024-017-0207-7">https://doi.org/10.1186/s13024-017-0207-7</a>.</div>
</div>
<div id="ref-puri2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[11] </div><div class="csl-right-inline">Puri TA, Richard JE, Galea LAM. Beyond sex differences: short- and long-term effects of pregnancy on the brain. Trends in Neurosciences 2023;46:459–71. <a href="https://doi.org/10.1016/j.tins.2023.03.010">https://doi.org/10.1016/j.tins.2023.03.010</a>.</div>
</div>
<div id="ref-pawluski2007" class="csl-entry" role="listitem">
<div class="csl-left-margin">[12] </div><div class="csl-right-inline">Pawluski JL, Galea LAM. Reproductive experience alters hippocampal neurogenesis during the postpartum period in the dam. Neuroscience 2007;149:53–67. <a href="https://doi.org/10.1016/j.neuroscience.2007.07.031">https://doi.org/10.1016/j.neuroscience.2007.07.031</a>.</div>
</div>
<div id="ref-eid2019" class="csl-entry" role="listitem">
<div class="csl-left-margin">[13] </div><div class="csl-right-inline">Eid RS, Chaiton JA, Lieblich SE, Bodnar TS, Weinberg J, Galea LAM. Early and late effects of maternal experience on hippocampal neurogenesis, microglia, and the circulating cytokine milieu. Neurobiology of Aging 2019;78:1–17. <a href="https://doi.org/10.1016/j.neurobiolaging.2019.01.021">https://doi.org/10.1016/j.neurobiolaging.2019.01.021</a>.</div>
</div>
<div id="ref-Hoekzema2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[14] </div><div class="csl-right-inline">Hoekzema E, Barba-Müller E, Pozzobon C, Picado M, Lucco F, García-García D, et al. Pregnancy leads to long-lasting changes in human brain structure. Nature Neuroscience 2016;20:287–96. <a href="https://doi.org/10.1038/nn.4458">https://doi.org/10.1038/nn.4458</a>.</div>
</div>
<div id="ref-de2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[15] </div><div class="csl-right-inline">Lange A-MG de, Barth C, Kaufmann T, Anatürk M, Suri S, Ebmeier KP, et al. The maternal brain: Region<span>-</span>specific patterns of brain aging are traceable decades after childbirth. Human Brain Mapping 2020;41:4718–29. <a href="https://doi.org/10.1002/hbm.25152">https://doi.org/10.1002/hbm.25152</a>.</div>
</div>
<div id="ref-colucci2006" class="csl-entry" role="listitem">
<div class="csl-left-margin">[16] </div><div class="csl-right-inline">Colucci M, Cammarata S, Assini A, Croce R, Clerici F, Novello C, et al. The number of pregnancies is a risk factor for Alzheimer’s disease. European Journal of Neurology 2006;13:1374–7. <a href="https://doi.org/10.1111/j.1468-1331.2006.01520.x">https://doi.org/10.1111/j.1468-1331.2006.01520.x</a>.</div>
</div>
<div id="ref-Fox2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">[17] </div><div class="csl-right-inline">Fox M, Berzuini C, Knapp LA, Glynn LM. Women<span>’</span>s Pregnancy Life History and Alzheimer<span>’</span>s Risk: Can Immunoregulation Explain the Link? American Journal of Alzheimer’s Disease &amp; Other Dementias® 2018;33:516–26. <a href="https://doi.org/10.1177/1533317518786447">https://doi.org/10.1177/1533317518786447</a>.</div>
</div>
<div id="ref-Fox2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">[18] </div><div class="csl-right-inline">Fox M, Berzuini C, Knapp LA. Cumulative estrogen exposure, number of menstrual cycles, and Alzheimer’s risk in a cohort of British women. Psychoneuroendocrinology 2013;38:2973–82. <a href="https://doi.org/10.1016/j.psyneuen.2013.08.005">https://doi.org/10.1016/j.psyneuen.2013.08.005</a>.</div>
</div>
<div id="ref-wolfova2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">[19] </div><div class="csl-right-inline">Wolfova K, Hubbard RA, Brennan Kearns P, Chang VW, Crane P, LaCroix AZ, et al. Number of children and risk of dementia: a cohort study. Journal of Epidemiology and Community Health 2024;79:280–7. <a href="https://doi.org/10.1136/jech-2024-222717">https://doi.org/10.1136/jech-2024-222717</a>.</div>
</div>
<div id="ref-Beeri2009a" class="csl-entry" role="listitem">
<div class="csl-left-margin">[20] </div><div class="csl-right-inline">Beeri MS, Rapp M, Schmeidler J, Reichenberg A, Purohit DP, Perl DP, et al. Number of children is associated with neuropathology of Alzheimer’s disease in women. Neurobiology of Aging 2009;30:1184–91. <a href="https://doi.org/10.1016/j.neurobiolaging.2007.11.011">https://doi.org/10.1016/j.neurobiolaging.2007.11.011</a>.</div>
</div>
<div id="ref-Jung2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[21] </div><div class="csl-right-inline">Jung JH, Lee GW, Lee JH, Byun MS, Yi D, Jeon SY, et al. Multiparity, brain atrophy, and cognitive decline. Frontiers in Aging Neuroscience 2020;12. <a href="https://doi.org/10.3389/fnagi.2020.00159">https://doi.org/10.3389/fnagi.2020.00159</a>.</div>
</div>
<div id="ref-lee2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">[22] </div><div class="csl-right-inline">Lee BH, Cevizci M, Lieblich SE, Ibrahim M, Wen Y, Eid RS, et al. Exploring the parity paradox: Differential effects on neuroplasticity and inflammation by APOEe4 genotype at middle age. Brain, Behavior, and Immunity 2024;120:54–70. <a href="https://doi.org/10.1016/j.bbi.2024.05.019">https://doi.org/10.1016/j.bbi.2024.05.019</a>.</div>
</div>
<div id="ref-parizkova2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">[23] </div><div class="csl-right-inline">Parizkova M, Lerch O, Moffat SD, Andel R, Mazancova AF, Nedelska Z, et al. The effect of Alzheimer’s disease on spatial navigation strategies. Neurobiology of Aging 2018;64:107–15. <a href="https://doi.org/10.1016/j.neurobiolaging.2017.12.019">https://doi.org/10.1016/j.neurobiolaging.2017.12.019</a>.</div>
</div>
<div id="ref-molinuevo2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[24] </div><div class="csl-right-inline">Molinuevo JL, Gramunt N, Gispert JD, Fauria K, Esteller M, Minguillon C, et al. The ALFA project: A research platform to identify early pathophysiological features of Alzheimer’s disease. Alzheimer’s &amp; Dementia: Translational Research &amp; Clinical Interventions 2016;2:82–92. <a href="https://doi.org/10.1016/j.trci.2016.02.003">https://doi.org/10.1016/j.trci.2016.02.003</a>.</div>
</div>
<div id="ref-Ashburner2007" class="csl-entry" role="listitem">
<div class="csl-left-margin">[25] </div><div class="csl-right-inline">Ashburner J. A fast diffeomorphic image registration algorithm. NeuroImage 2007;38:95–113. <a href="https://doi.org/10.1016/j.neuroimage.2007.07.007">https://doi.org/10.1016/j.neuroimage.2007.07.007</a>.</div>
</div>
<div id="ref-Yushkevich2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">[26] </div><div class="csl-right-inline">Yushkevich PA, Pluta JB, Wang H, Xie L, Ding S-L, Gertje EC, et al. Automated volumetry and regional thickness analysis of hippocampal subfields and medial temporal cortical structures in mild cognitive impairment. Human Brain Mapping 2014;36:258–87. <a href="https://doi.org/10.1002/hbm.22627">https://doi.org/10.1002/hbm.22627</a>.</div>
</div>
<div id="ref-Donohue2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">[27] </div><div class="csl-right-inline">Donohue MC, Sperling RA, Salmon DP, Rentz DM, Raman R, Thomas RG, et al. The Preclinical Alzheimer Cognitive Composite. JAMA Neurology 2014;71:961. <a href="https://doi.org/10.1001/jamaneurol.2014.803">https://doi.org/10.1001/jamaneurol.2014.803</a>.</div>
</div>
<div id="ref-pievani2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">[28] </div><div class="csl-right-inline">Pievani M, Galluzzi S, Thompson PM, Rasser PE, Bonetti M, Frisoni GB. APOE4 is associated with greater atrophy of the hippocampal formation in Alzheimer’s disease. NeuroImage 2011;55:909–19. <a href="https://doi.org/10.1016/j.neuroimage.2010.12.081">https://doi.org/10.1016/j.neuroimage.2010.12.081</a>.</div>
</div>
<div id="ref-pritschet2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">[29] </div><div class="csl-right-inline">Pritschet L, Taylor CM, Cossio D, Faskowitz J, Santander T, Handwerker DA, et al. Neuroanatomical changes observed over the course of a human pregnancy. Nature Neuroscience 2024;27:2253–60. <a href="https://doi.org/10.1038/s41593-024-01741-0">https://doi.org/10.1038/s41593-024-01741-0</a>.</div>
</div>
<div id="ref-scheltens1992a" class="csl-entry" role="listitem">
<div class="csl-left-margin">[30] </div><div class="csl-right-inline">Scheltens P, Weinstein HC, Leys D. Neuro-imaging in the diagnosis of Alzheimer’s disease I. Computer tomography and magnetic resonance imaging. Clinical Neurology and Neurosurgery 1992;94:277–89. <a href="https://doi.org/10.1016/0303-8467(92)90175-3">https://doi.org/10.1016/0303-8467(92)90175-3</a>.</div>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>