<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Clazz">

<title>Parity and AD specific neurodegeneration</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="ad_signatures_files/libs/clipboard/clipboard.min.js"></script>
<script src="ad_signatures_files/libs/quarto-html/quarto.js"></script>
<script src="ad_signatures_files/libs/quarto-html/popper.min.js"></script>
<script src="ad_signatures_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ad_signatures_files/libs/quarto-html/anchor.min.js"></script>
<link href="ad_signatures_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ad_signatures_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ad_signatures_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ad_signatures_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ad_signatures_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design"><span class="header-section-number">3.1</span> Study design</a></li>
  <li><a href="#participants" id="toc-participants" class="nav-link" data-scroll-target="#participants"><span class="header-section-number">3.2</span> Participants</a></li>
  <li><a href="#procedures" id="toc-procedures" class="nav-link" data-scroll-target="#procedures"><span class="header-section-number">3.3</span> Procedures</a>
  <ul class="collapse">
  <li><a href="#demographics" id="toc-demographics" class="nav-link" data-scroll-target="#demographics"><span class="header-section-number">3.3.1</span> Demographics</a></li>
  <li><a href="#imaging-data-preprocessing" id="toc-imaging-data-preprocessing" class="nav-link" data-scroll-target="#imaging-data-preprocessing"><span class="header-section-number">3.3.2</span> Imaging data preprocessing</a></li>
  <li><a href="#automatic-segmentation-of-hippocampal-subfields" id="toc-automatic-segmentation-of-hippocampal-subfields" class="nav-link" data-scroll-target="#automatic-segmentation-of-hippocampal-subfields"><span class="header-section-number">3.3.3</span> Automatic Segmentation of Hippocampal Subfields</a></li>
  <li><a href="#lumbar-puncture" id="toc-lumbar-puncture" class="nav-link" data-scroll-target="#lumbar-puncture"><span class="header-section-number">3.3.4</span> Lumbar puncture</a></li>
  <li><a href="#cognitive-measures" id="toc-cognitive-measures" class="nav-link" data-scroll-target="#cognitive-measures"><span class="header-section-number">3.3.5</span> Cognitive measures</a></li>
  </ul></li>
  <li><a href="#statistical-analyses" id="toc-statistical-analyses" class="nav-link" data-scroll-target="#statistical-analyses"><span class="header-section-number">3.4</span> Statistical analyses</a>
  <ul class="collapse">
  <li><a href="#variable-definition" id="toc-variable-definition" class="nav-link" data-scroll-target="#variable-definition"><span class="header-section-number">3.4.1</span> Variable definition</a></li>
  <li><a href="#covariate-selection" id="toc-covariate-selection" class="nav-link" data-scroll-target="#covariate-selection"><span class="header-section-number">3.4.2</span> Covariate selection</a></li>
  <li><a href="#cross-sectional-analyses" id="toc-cross-sectional-analyses" class="nav-link" data-scroll-target="#cross-sectional-analyses"><span class="header-section-number">3.4.3</span> Cross-sectional analyses</a></li>
  <li><a href="#longitudinal-analyses" id="toc-longitudinal-analyses" class="nav-link" data-scroll-target="#longitudinal-analyses"><span class="header-section-number">3.4.4</span> Longitudinal analyses</a></li>
  <li><a href="#post-hoc-analyses" id="toc-post-hoc-analyses" class="nav-link" data-scroll-target="#post-hoc-analyses"><span class="header-section-number">3.4.5</span> Post-hoc analyses</a></li>
  <li><a href="#missing-data" id="toc-missing-data" class="nav-link" data-scroll-target="#missing-data"><span class="header-section-number">3.4.6</span> Missing data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#descriptive-results" id="toc-descriptive-results" class="nav-link" data-scroll-target="#descriptive-results"><span class="header-section-number">4.1</span> Descriptive results</a></li>
  <li><a href="#whole-hippocampal-volume" id="toc-whole-hippocampal-volume" class="nav-link" data-scroll-target="#whole-hippocampal-volume"><span class="header-section-number">4.2</span> Whole Hippocampal volume</a></li>
  <li><a href="#cognitive-trajectory" id="toc-cognitive-trajectory" class="nav-link" data-scroll-target="#cognitive-trajectory"><span class="header-section-number">4.3</span> Cognitive trajectory</a></li>
  <li><a href="#post-hoc" id="toc-post-hoc" class="nav-link" data-scroll-target="#post-hoc"><span class="header-section-number">4.4</span> Post-Hoc</a>
  <ul class="collapse">
  <li><a href="#hippocampal-subfields" id="toc-hippocampal-subfields" class="nav-link" data-scroll-target="#hippocampal-subfields"><span class="header-section-number">4.4.1</span> Hippocampal subfields</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="header-section-number">6</span> Appendix</a>
  <ul class="collapse">
  <li><a href="#mri-data-acquisition" id="toc-mri-data-acquisition" class="nav-link" data-scroll-target="#mri-data-acquisition"><span class="header-section-number">6.1</span> MRI data acquisition</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Parity and AD specific neurodegeneration</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Clazz </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abstract</h1>
<p>300 words</p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
</section>
<section id="methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methods</h1>
<section id="study-design" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="study-design"><span class="header-section-number">3.1</span> Study design</h2>
<p>This study was realised within the context of the The ALFA+ project, a longitudinal observational cohort of healthly middle aged adults. This project currently takes place in the city of Barcelona, Spain, at the BarcelonaBeta Brain Research Center. Visit 1 was collected between 2013 and 2015, and Visit 2 between 2016 and 2019 Visit 3 is still undergoing. The ALFA study protocol was approved by the Independent Ethics Committee Parc de Salut Mar Barcelona (and registered at Clinicaltrials.gov, NCT01835717). For a more detailed description of the cohort see Molinuevo et al.<span class="citation" data-cites="molinuevo2016">[<a href="#ref-molinuevo2016" role="doc-biblioref">1</a>]</span>. Our sample includes all the women of the ALFA+ cohort, who were all postmenopausal at visit 1.</p>
</section>
<section id="participants" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="participants"><span class="header-section-number">3.2</span> Participants</h2>
<p>In brief, inclusion criteria were being cognitively normal, Spanish and/or Catalan-speaking, being aged between 45 and 74 years and agreing with the study procedures and tests. A close relative was involved in the volunteer’s functional evaluation and both of them had to grant their written informed consent. Exclusion criterias Exclusion criteria were (1) Cognitive performance falling outside the established cutoffs, (2) a Clinical Dementia Rating above 0, (3) major psychiatric disorders (according to DSM-IV-TR), (4) Severe auditory and/or visual disorder, neurodevelopmental and/or psychomotor disorder, (5) Signiﬁcant diseases that could currently interfere with cognition, (6) neurological disorders, (7) Brain injuries and (8) a suspected pattern of family autosomal dominant AD.</p>
<p>In addition to the above exclusion criteria, women with history of cardiovascular related gestational disease, such as preeclampsia, were excluded from our sample for analysis.</p>
<p>Participants were recruited via advertisement campaigns in newspapers and followed-up via email and phonecalls.</p>
</section>
<section id="procedures" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="procedures"><span class="header-section-number">3.3</span> Procedures</h2>
<section id="demographics" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="demographics"><span class="header-section-number">3.3.1</span> Demographics</h3>
<p>Demographic data was collected via oral questions administered by a clinician. Sex was self reported, as well as gender and participants could choose from three options: male, female, or … Race and ethnicity were also self-reported.</p>
<p>Reproductive variables, such as number of biological kids, age at menopause, age at menarche and number of abortions, were self-reported at the baseline visit. In the subsequent visits, participants were also asked about hormonal replacement therapy.</p>
<p>Social variables such as years of education, household income, occupational attainment and civil status were also self-reported at baseline visit.</p>
</section>
<section id="imaging-data-preprocessing" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="imaging-data-preprocessing"><span class="header-section-number">3.3.2</span> Imaging data preprocessing</h3>
<p>GMV changes were computed voxel-wise using the pairwise longitudinal registration implemented in the statistical parametric mapping software (SPM, version 12) (<a href="https://www.fil.ion.ucl.ac.uk/spm/software/spm12/"><strong>https://www.fil.ion.ucl.ac.uk/spm/software/spm12/</strong></a>). The procedure involves a high-dimensional warping between consecutive T1-weighted scans, combining diffeomorphic and rigid-body registrations and incorporating a correction for field inhomogeneities. This procedure yields for each subject a parametric whole brain map encoding at each voxel the local tissue deformations that have occurred over time <span class="citation" data-cites="Ashburner2007">[<a href="#ref-Ashburner2007" role="doc-biblioref">2</a>]</span> . Individual deformation maps were inspected for sample homogeneity using the computational anatomy toolbox (CAT12) (<a href="http://dbm.neuro.unijena.de/cat/"><strong>http://dbm.neuro.unijena.de/cat/</strong></a>) and normalized to the Montreal Neurological Institute (MNI) space using diffeomorphic image registration with DARTEL30 and spatially smoothed with an 8-mm full width at half maximum (FWHM) Gaussian kernel before being submitted to group statistical analyses.</p>
</section>
<section id="automatic-segmentation-of-hippocampal-subfields" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="automatic-segmentation-of-hippocampal-subfields"><span class="header-section-number">3.3.3</span> Automatic Segmentation of Hippocampal Subfields</h3>
<p>Automatic Segmentation of Hippocampal Subfields (ASHS) software <span class="citation" data-cites="Yushkevich2015">[<a href="#ref-Yushkevich2015" role="doc-biblioref">3</a>]</span> was used on the T1 and inversion recovery (IR) images to segment the hippocampal formation in the following sub-regions: Brodmann areas 35 and 36, cornu Ammonis (CA) 1, 2 and 3, dentate gyrus (DG), entorhinal cortex (ERC), parahippocampus (PHC), subiculum (SUB), and sulcus (SUL). All segmentations were visually inspected before proceeding with the statistical analyses.</p>
</section>
<section id="lumbar-puncture" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4" class="anchored" data-anchor-id="lumbar-puncture"><span class="header-section-number">3.3.4</span> Lumbar puncture</h3>
<p>CSF was collected by lumbar puncture between 9 and 12 a.m. in polypropylene tubes. Samples were processed within 1 hour and centrifuged at 4°C for 10 minutes at 2000 g, stored in polypropylene tubes and frozen at -80°C. Core AD biomarkers (namely Ab42, Ab40, total Tau, and p tau) and other molecules of interest (such as YKL-40, neurogranin and Ab oligomers) were analyzed and determined in Prof.&nbsp;Kaj Blennow’s laboratory (Institute ofNeuroscience and Physiology, Department of Psychiatry and Neurochemistry, The Sahlgrenska Academy at the University of Gothenburg, Sweden).</p>
</section>
<section id="cognitive-measures" class="level3" data-number="3.3.5">
<h3 data-number="3.3.5" class="anchored" data-anchor-id="cognitive-measures"><span class="header-section-number">3.3.5</span> Cognitive measures</h3>
<p>The Preclinical Alzheimer Cognitive Composite (PACC) was developed to detect subtle cognitive changes in individuals who may be in the pre-clinical stages of AD <span class="citation" data-cites="Donohue2014">[<a href="#ref-Donohue2014" role="doc-biblioref">4</a>]</span>, and includes elements of the Memory Binding Test, the Coding subtest of WAIS-IV, and semantic fluency. Z-scores were computed for Visit 1 and 2.</p>
</section>
</section>
<section id="statistical-analyses" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="statistical-analyses"><span class="header-section-number">3.4</span> Statistical analyses</h2>
<p>All statistical analyses were conducted using R version 4.5.1.</p>
<section id="variable-definition" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="variable-definition"><span class="header-section-number">3.4.1</span> Variable definition</h3>
<p>Parity, defined as the number of biological children, was modeled as a continuous variable (0, 1, 2, 3, 4+). Parity was also modeled as a categorical variable (nulliparous, primiparous, multiparous) for sensitivity analyses but since this greatly reduces our statistical power we mainly considered direction of slope and effect size but not statistical significance. Time was calculated as the number of days between Visit 1 and Visit 2 for MRI scans and cognitive testing sessions. Aβ positivity was defined as a binary variable based on the CSF Aβ42/Aβ40 ratio, with participants classified as Aβ-positive if the ratio fell below the established cutoff of 0.071 pg/mL <span class="citation" data-cites="Milà-Alomà2020">[<a href="#ref-Milà-Alomà2020" role="doc-biblioref">5</a>]</span>.</p>
</section>
<section id="covariate-selection" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="covariate-selection"><span class="header-section-number">3.4.2</span> Covariate selection</h3>
<p>We used directed acyclic graph (DAG) methodology and Pearl’s backdoor criteria to identify confounders. Based on this approach, all models were adjusted for age at baseline and years of education, as these variables influence both the exposure and outcome, therefore making them confounders in our analysis. Models were additionally adjusted for APOE4 carrier status given the enrichment of ALFA+ participants for AD genetic risk factors. Models with hippocampal volumes as outcomes were further adjusted for total intracranial volume (TIV).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ad_signatures_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="cross-sectional-analyses" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="cross-sectional-analyses"><span class="header-section-number">3.4.3</span> Cross-sectional analyses</h3>
<p>We conducted simple linear regressions using Visit 1 data to examine cross-sectional associations between parity, Aβ positivity, and hippocampal volume. Parity was modeled both as a continuous variable and as a categorical variable (nulliparous, primiparous, and multiparous). Total hippocampal volume served as the continuous outcome variable. All models included age at baseline, APOE4 carrier status, years of education, and total intracranial volume as covariates.</p>
</section>
<section id="longitudinal-analyses" class="level3" data-number="3.4.4">
<h3 data-number="3.4.4" class="anchored" data-anchor-id="longitudinal-analyses"><span class="header-section-number">3.4.4</span> Longitudinal analyses</h3>
<p>Mixed-effects models were used to assess longitudinal effects on hippocampal volume. These models included a three-way interaction term between parity, Aβ positivity, and time (interval between Visit 1 and Visit 2), with the same covariates as the cross-sectional models.</p>
</section>
<section id="post-hoc-analyses" class="level3" data-number="3.4.5">
<h3 data-number="3.4.5" class="anchored" data-anchor-id="post-hoc-analyses"><span class="header-section-number">3.4.5</span> Post-hoc analyses</h3>
<p>Post-hoc linear regressions were performed on Visit 1 data to explore the interaction between parity and Aβ positivity on individual hippocampal subfield volumes. Given the exploratory nature of these analyses, results are reported without correction for multiple comparisons.</p>
</section>
<section id="missing-data" class="level3" data-number="3.4.6">
<h3 data-number="3.4.6" class="anchored" data-anchor-id="missing-data"><span class="header-section-number">3.4.6</span> Missing data</h3>
<p>Data imputation methods were implemented using the mice package in R (v.3.18.0) on covariates, but not exposure or outcome variables. For continous variables, predictive mean matching with 5 donors was used. For categorical variables, logistic regression was used.</p>
</section>
</section>
</section>
<section id="results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<section id="descriptive-results" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="descriptive-results"><span class="header-section-number">4.1</span> Descriptive results</h2>
<div class="cell">
<div class="cell-output-display">
<div id="cjrvketnvy" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#cjrvketnvy table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#cjrvketnvy thead, #cjrvketnvy tbody, #cjrvketnvy tfoot, #cjrvketnvy tr, #cjrvketnvy td, #cjrvketnvy th {
  border-style: none;
}

#cjrvketnvy p {
  margin: 0;
  padding: 0;
}

#cjrvketnvy .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cjrvketnvy .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cjrvketnvy .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cjrvketnvy .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cjrvketnvy .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cjrvketnvy .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cjrvketnvy .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cjrvketnvy .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cjrvketnvy .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cjrvketnvy .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cjrvketnvy .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cjrvketnvy .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cjrvketnvy .gt_spanner_row {
  border-bottom-style: hidden;
}

#cjrvketnvy .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cjrvketnvy .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cjrvketnvy .gt_from_md > :first-child {
  margin-top: 0;
}

#cjrvketnvy .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cjrvketnvy .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cjrvketnvy .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cjrvketnvy .gt_row_group_first td {
  border-top-width: 2px;
}

#cjrvketnvy .gt_row_group_first th {
  border-top-width: 2px;
}

#cjrvketnvy .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cjrvketnvy .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cjrvketnvy .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cjrvketnvy .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cjrvketnvy .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#cjrvketnvy .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cjrvketnvy .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cjrvketnvy .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cjrvketnvy .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cjrvketnvy .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cjrvketnvy .gt_left {
  text-align: left;
}

#cjrvketnvy .gt_center {
  text-align: center;
}

#cjrvketnvy .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cjrvketnvy .gt_font_normal {
  font-weight: normal;
}

#cjrvketnvy .gt_font_bold {
  font-weight: bold;
}

#cjrvketnvy .gt_font_italic {
  font-style: italic;
}

#cjrvketnvy .gt_super {
  font-size: 65%;
}

#cjrvketnvy .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#cjrvketnvy .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cjrvketnvy .gt_indent_1 {
  text-indent: 5px;
}

#cjrvketnvy .gt_indent_2 {
  text-indent: 10px;
}

#cjrvketnvy .gt_indent_3 {
  text-indent: 15px;
}

#cjrvketnvy .gt_indent_4 {
  text-indent: 20px;
}

#cjrvketnvy .gt_indent_5 {
  text-indent: 25px;
}

#cjrvketnvy .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#cjrvketnvy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Number of childbirths</strong></th>
<th id="n" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>N</strong></th>
<th id="stat_1" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>0</strong><br>
N = 39<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_2" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>1</strong><br>
N = 54<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_3" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>2</strong><br>
N = 126<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_4" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>3</strong><br>
N = 27<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_5" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>4+</strong><br>
N = 8<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">Age at first visit, Mean (SD)</td>
<td class="gt_row gt_center" headers="n">254</td>
<td class="gt_row gt_center" headers="stat_1">58.6 (55.3, 62.3)</td>
<td class="gt_row gt_center" headers="stat_2">59.9 (56.7, 63.7)</td>
<td class="gt_row gt_center" headers="stat_3">62.6 (58.4, 65.1)</td>
<td class="gt_row gt_center" headers="stat_4">61.2 (58.1, 64.8)</td>
<td class="gt_row gt_center" headers="stat_5">66.2 (61.5, 68.6)</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">Aβ status, Count (%)</td>
<td class="gt_row gt_center" headers="n">229</td>
<td class="gt_row gt_center" headers="stat_1"><br>
</td>
<td class="gt_row gt_center" headers="stat_2"><br>
</td>
<td class="gt_row gt_center" headers="stat_3"><br>
</td>
<td class="gt_row gt_center" headers="stat_4"><br>
</td>
<td class="gt_row gt_center" headers="stat_5"><br>
</td>
<td class="gt_row gt_center" headers="p.value">0.8</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Aβ-</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_1">23 (70%)</td>
<td class="gt_row gt_center" headers="stat_2">34 (69%)</td>
<td class="gt_row gt_center" headers="stat_3">72 (64%)</td>
<td class="gt_row gt_center" headers="stat_4">19 (70%)</td>
<td class="gt_row gt_center" headers="stat_5">4 (50%)</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Aβ+</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_1">10 (30%)</td>
<td class="gt_row gt_center" headers="stat_2">15 (31%)</td>
<td class="gt_row gt_center" headers="stat_3">40 (36%)</td>
<td class="gt_row gt_center" headers="stat_4">8 (30%)</td>
<td class="gt_row gt_center" headers="stat_5">4 (50%)</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">APOE-E4 carrier, Count (%)</td>
<td class="gt_row gt_center" headers="n">254</td>
<td class="gt_row gt_center" headers="stat_1"><br>
</td>
<td class="gt_row gt_center" headers="stat_2"><br>
</td>
<td class="gt_row gt_center" headers="stat_3"><br>
</td>
<td class="gt_row gt_center" headers="stat_4"><br>
</td>
<td class="gt_row gt_center" headers="stat_5"><br>
</td>
<td class="gt_row gt_center" headers="p.value">0.4</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Carrier</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_1">19 (49%)</td>
<td class="gt_row gt_center" headers="stat_2">23 (43%)</td>
<td class="gt_row gt_center" headers="stat_3">72 (57%)</td>
<td class="gt_row gt_center" headers="stat_4">13 (48%)</td>
<td class="gt_row gt_center" headers="stat_5">3 (38%)</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Non-Carrier</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_1">20 (51%)</td>
<td class="gt_row gt_center" headers="stat_2">31 (57%)</td>
<td class="gt_row gt_center" headers="stat_3">54 (43%)</td>
<td class="gt_row gt_center" headers="stat_4">14 (52%)</td>
<td class="gt_row gt_center" headers="stat_5">5 (63%)</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">Time between visits (years), Mean (SD)</td>
<td class="gt_row gt_center" headers="n">203</td>
<td class="gt_row gt_center" headers="stat_1">3.26 (3.03, 3.48)</td>
<td class="gt_row gt_center" headers="stat_2">3.42 (3.13, 3.72)</td>
<td class="gt_row gt_center" headers="stat_3">3.24 (3.01, 3.48)</td>
<td class="gt_row gt_center" headers="stat_4">3.23 (3.03, 3.74)</td>
<td class="gt_row gt_center" headers="stat_5">3.32 (2.93, 3.76)</td>
<td class="gt_row gt_center" headers="p.value">0.13</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">Education (years), Mean (SD)</td>
<td class="gt_row gt_center" headers="n">254</td>
<td class="gt_row gt_center" headers="stat_1">17.0 (12.0, 18.0)</td>
<td class="gt_row gt_center" headers="stat_2">12.0 (10.0, 15.0)</td>
<td class="gt_row gt_center" headers="stat_3">12.0 (10.0, 16.0)</td>
<td class="gt_row gt_center" headers="stat_4">13.0 (10.0, 18.0)</td>
<td class="gt_row gt_center" headers="stat_5">11.0 (8.0, 12.0)</td>
<td class="gt_row gt_center" headers="p.value">0.013</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="odd">
<td colspan="8" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Median (Q1, Q3); n (%)</td>
</tr>
<tr class="even">
<td colspan="8" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> Kruskal-Wallis rank sum test; Fisher’s exact test</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>254 female participants from the ALFA+ project were included in our analyses. Visit 1 included MRI data from 241 participants and cognitive testing from 234 participants. Visit 2 included MRI data from 203 participants and cognitive testing from 203 participants. Average time between visits was 3.32 years.</p>
<p>Table 1 shows demographics and characteristics of the ALFA+ cohort for all aprticipants included in Visit 1, grouped by parity. Participants with higher parity were significantly more likely to be older. No difference was seen between groups regarding Aβ status and APOE-ε4 carriership.</p>
<ul>
<li>Do we have dropout data for ALFA? and reasons for dropout?</li>
</ul>
</section>
<section id="whole-hippocampal-volume" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="whole-hippocampal-volume"><span class="header-section-number">4.2</span> Whole Hippocampal volume</h2>
<p>No significant main effect of parity on hipocampal volume were found cross-sectionally at at Visit 1. The interaction between parity and Aβ status was significant (β = -137.727, SE = 65.209, p = 0.036), showing that Aβ- women exhibited a positive relationship between parity and hippocampal volume, whilst Aβ- women showed the opposite (Figure X).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ad_signatures_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Splitting women between nulliparous, primiparous and multiparous seemed to indicate that this interaction might only take effect in multiparous women (Figure x).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ad_signatures_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>We found no significant independent effect of parity on whole hippocampal volume trajectory. However, a significant effect of parity and Aβ interaction was found (β = -134.103, SE = 65.295, p = 0.041), such that Aβ- women showed a positive relationship between parity and hippocampal volume, whilst Aβ- women showed the opposite. This association was independent from time.</p>
<p>Again, splitting our subjects between nulliparous, primiparous and multiparous showed the direction of this interaction might only take effect in multiparous women.</p>
</section>
<section id="cognitive-trajectory" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="cognitive-trajectory"><span class="header-section-number">4.3</span> Cognitive trajectory</h2>
<p>No main effect of parity or interaction between parity and Aß status was found on PACC when looking only at baseline data.</p>
<p>In the context of longitudinal data, introducing a 3-way interaction between parity, time and Aß positivity revealed a moderate yet significant effect on PACC z-score change (β = -9.636^{-5}, p=0.033). Results suggest that Aß- women showed lesser cognitive decline with a higher number of children, and Aβ+ women the opposite (Figure X).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ad_signatures_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Reproducing the analysis using our 3 parity groups showed that the direction of the interaction was present in both primiparous and multiparous groups, but the estimate was bigger in the latter one (Figure X).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ad_signatures_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="post-hoc" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="post-hoc"><span class="header-section-number">4.4</span> Post-Hoc</h2>
<section id="hippocampal-subfields" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="hippocampal-subfields"><span class="header-section-number">4.4.1</span> Hippocampal subfields</h3>
<p>No significant main effect of parity was found in any of the hippocampal subfields. However, there was a significant effect of the interaction between parity and Aβ on the dentate gyrus (β = 5.75, SE = 3.532, p = 0.105), and a trending effect of this same interaction in the subiculum (β = -0.38, SE = 1.81, p = 0.834). The direction of the effect followed the same as for the whole hippocampus, where Aβ- women showed a positive relationship between parity and hippocampal volume, whilst Aβ- women showed the opposite (Figure X)</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ad_signatures_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="discussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion</h1>
<p>We aimed to investigate the impact of parity on hippocampal subfield volumes and relation to AD pathology in post-menopausal women at risk of AD and men who share similar age and AD risk. Our results suggest that…</p>
<p>Parity interacts with amyloid pathology to influence neurodegeneration and cognition. In our sample, parity was not associated with hippocampal volume size directly but appeared to moderate the effet of amyloid accumulation on hippocampal volume. In the context of low amyloid, female participants appeared to exhibit greater volumes especially in the subiculum and dentate gyrus area.</p>
<p>Interestingly, introducing variables that serve as proxy for hormonal exposure, such as HRT use and reproductive span, seemed to explain some of this effet in the dentate gyrus area but not in the subiculum.</p>
<p>Similarly, parity does not impact PACC score independently but appears to moderate the impact of amyloid pathology on cognitive trajectory. In the context of low amyloid, female participants with higher parity showed lesser cognitive decline. However, this effect was very small, especially compared with the effect of other variables, like education. Whilst including covariates related to sex steroid exposure did not modify this relationship, including household income did.</p>
<p>Mediation analyses trying to identify a possible mechanism behind the parity and amyloid accumulation did not yield any suitable candidates.</p>
<p>mention liisa galea’s recent findings and how we don’t find an interaction with APOE?</p>
<p>The biggest limitation of this study is the lack of hormonal measurements. By only using proxy measurements, we are only able to estimate the role of sex steroid hormones in the results found, but cannot make any definitive conclusions. It is very possible the role of sex hormones in our observatioins was underestimated due to this missing variable. In addition to this, the ALFA+ cohort is very homogeneous: participants are majoritarily caucasian whites, from middle and upper-middle class background, who were selected due to their impeccable health records. Therefore, we must use cuation when generalising our results to a wider population. Additionally, our sample lacked highly multiparous individuals. Previous studies on the effect of parity on cognition and neurodegeneration have found an inverted u-shaped relation between parity and outcome measures, indicating that our lack of women having had more than 4 children might be leading to an incomplete picture of the phenomenon.</p>
</section>
<section id="appendix" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Appendix</h1>
<section id="mri-data-acquisition" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="mri-data-acquisition"><span class="header-section-number">6.1</span> MRI data acquisition</h2>
<p>MRI scans were acquired on a in-house 3.0 T scanner (GE Discovery MR750 W 3 T) using the same protocol for all participants, which included one T1- and three T2- weighted sequences. The 3D-T1w sequence was designed with an isotropic voxel size of1mm3 and a matrix size of256x256x160 (TR/TE/TI = 8.0/3.7/450 ms, NSA = 1, flip angle = 8°). Three 3D-T2w sequences, with a voxel size of1 mm× 1 mm× 3 mm, were also used: fluid attenuation inversion recovery (FLAIR: TR/TE/ TI = 11,000/90/2600 ms, flip angle = 160°), fast spin echo (FSE: TR/TE = 5000/85 ms, flip angle = 110°) and, gradient echo (GRE: TR/TE = 1300/23 ms, flip angle = 15°). All scans were visually assessed to verify their quality and to detect incidental findings by a trained neuroradiologist and have been reported elsewhere (Brugulat-Serrat et al.&nbsp;2017). At visit 1, ten participants were excluded due to the presence of a meningioma, as well as 37 participants due to susceptibility, motion artefacts or segmentation problems, resulting in a total of 561 images available for subsequent analysis. At Visit 2, … The medial temporal lobe atrophy was assessed by Medial Temporal Atrophy scale <span class="citation" data-cites="scheltens1992a">[<a href="#ref-scheltens1992a" role="doc-biblioref">6</a>]</span>.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-molinuevo2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">Molinuevo JL, Gramunt N, Gispert JD, Fauria K, Esteller M, Minguillon C, et al. The ALFA project: A research platform to identify early pathophysiological features of Alzheimer’s disease. Alzheimer’s &amp; Dementia: Translational Research &amp; Clinical Interventions 2016;2:82–92. <a href="https://doi.org/10.1016/j.trci.2016.02.003">https://doi.org/10.1016/j.trci.2016.02.003</a>.</div>
</div>
<div id="ref-Ashburner2007" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">Ashburner J. A fast diffeomorphic image registration algorithm. NeuroImage 2007;38:95–113. <a href="https://doi.org/10.1016/j.neuroimage.2007.07.007">https://doi.org/10.1016/j.neuroimage.2007.07.007</a>.</div>
</div>
<div id="ref-Yushkevich2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">Yushkevich PA, Pluta JB, Wang H, Xie L, Ding S-L, Gertje EC, et al. Automated volumetry and regional thickness analysis of hippocampal subfields and medial temporal cortical structures in mild cognitive impairment. Human Brain Mapping 2014;36:258–87. <a href="https://doi.org/10.1002/hbm.22627">https://doi.org/10.1002/hbm.22627</a>.</div>
</div>
<div id="ref-Donohue2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">Donohue MC, Sperling RA, Salmon DP, Rentz DM, Raman R, Thomas RG, et al. The Preclinical Alzheimer Cognitive Composite. JAMA Neurology 2014;71:961. <a href="https://doi.org/10.1001/jamaneurol.2014.803">https://doi.org/10.1001/jamaneurol.2014.803</a>.</div>
</div>
<div id="ref-Milà-Alomà2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">Milà-Alomà M, Salvadó G, Gispert JD, Vilor-Tejedor N, Grau-Rivera O, Sala-Vila A, et al. Amyloid beta, tau, synaptic, neurodegeneration, and glial biomarkers in the preclinical stage of the Alzheimer’s <span><em>continuum</em></span>. Alzheimer’s &amp; Dementia 2020;16:1358–71. <a href="https://doi.org/10.1002/alz.12131">https://doi.org/10.1002/alz.12131</a>.</div>
</div>
<div id="ref-scheltens1992a" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline">Scheltens P, Weinstein HC, Leys D. Neuro-imaging in the diagnosis of Alzheimer’s disease I. Computer tomography and magnetic resonance imaging. Clinical Neurology and Neurosurgery 1992;94:277–89. <a href="https://doi.org/10.1016/0303-8467(92)90175-3">https://doi.org/10.1016/0303-8467(92)90175-3</a>.</div>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>